#! /usr/bin/env node

var exec = require('child_process').exec
var version = process.argv[2];

if (!version) {
  throw new Error('Provide a new version (vX.X.X)')
} else if (version[0] !== 'v') {
  version = 'v' + version
}

var commands = ['gulp dist',
'git add -A',
'git commit -m ' + version,
'git tag ' + version,
'git push',
'git push --tags',
'bower version',
'npm version ' + version,
'npm publish']

const run = (commands) => {
  if (commands && commands.length) {
    const stream = exec(commands.shift(), run)

    stream.stdout.on('data', (data) => {
      console.log(data);
    });

    stream.stderr.on('data', (data) => {
      console.log(data);
    });

    stream.on('exit', (code) => {
      run(commands);
    });
  }
}

run(commands)
