#! /usr/bin/env node

var exec = require('child_process').exec
var version = process.argv[2];

if (!version) {
  throw new Error('Provide a new version (vX.X.X)')
} else if (version[0] !== 'v') {
  version = 'v' + version
}

var commands = ['gulp dist',
'git add -A',
'git commit -m ' + version,
'git tag ' + version,
'git push',
'git push --tags',
'npm version ' + version,
'npm publish']

function run(cmd, cb) {
  if (commands.length) {
    exec(commands.shift(), run)
  }
}

run()
