#! /usr/bin/env node

const version = process.argv[2];
console.log(version[0]);
if (!version) {
  throw new Error('Provide a new version (vX.X.X)')
} else if (version[0] !== 'v') {
  version = 'v' + version
}

const exec = require('child_process').exec,
      write = require('fs').writeFileSync;

['bower.json', 'package.json'].forEach(file => {
  console.log(version, version.substring(1));
  const package = require(`./${file}`)
  package.version = version.substring(1);
  write(`./${file}`, JSON.stringify(package, null, 2), 'utf-8');
})

const loop = (commands) => {
  if (commands && commands.length) {
    const stream = exec(commands.shift())
    stream.stdout.on('data', (data) => console.log(data));
    stream.stderr.on('data', (error) => {
      console.error(error);
    });
    stream.on('exit', () => loop(commands));
  }
}

loop([
  'gulp build',
  'git add -A',
  'git commit -m ' + version,
  'git tag ' + version,
  'git push',
  'git push --tags',
  'npm publish'
])
